apiVersion: 1
datasources:
  - name: WorldCupPostgres
    uid: worldcup_pg
    type: postgres
    access: proxy
    url: postgres:5432
    user: user
    secureJsonData:
      password: password
    jsonData:
      database: worldcup
      sslmode: disable
      postgresVersion: 1700
    isDefault: true
    editable: true